-- MySQL Script generated by MySQL Workbench
-- Thu Feb 18 12:21:44 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Time`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Time` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Time` (
  `Time_ID` INT NOT NULL AUTO_INCREMENT,
  `Year` INT NOT NULL,
  `Month` INT NOT NULL,
  `Date` INT NOT NULL,
  `Clock_Time` DATETIME NOT NULL,
  PRIMARY KEY (`Time_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Location` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Location` (
  `Symbol` VARCHAR(45) NOT NULL,
  `Location` VARCHAR(45) NOT NULL,
  `GPS.Coordinates` VARCHAR(45) NOT NULL,
  `Elevation` DECIMAL(5) NOT NULL,
  `Aspect` VARCHAR(45) NOT NULL,
  `Topographical_Description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Symbol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sensor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Sensor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Sensor` (
  `Serial_Number` INT NOT NULL,
  `Location_Symbol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Serial_Number`),
  INDEX `Location_Symbol_idx` (`Location_Symbol` ASC),
  CONSTRAINT `Location_Symbol`
    FOREIGN KEY (`Location_Symbol`)
    REFERENCES `mydb`.`Location` (`Symbol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Measurement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Measurement` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Measurement` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Temperature` INT NOT NULL,
  `Time_ID` INT NOT NULL,
  `Sensor_Symbol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Time_ID_idx` (`Time_ID` ASC),
  INDEX `Sensor_Symbol_idx` (`Sensor_Symbol` ASC),
  CONSTRAINT `Time_ID`
    FOREIGN KEY (`Time_ID`)
    REFERENCES `mydb`.`Time` (`Time_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Sensor_Symbol`
    FOREIGN KEY (`Sensor_Symbol`)
    REFERENCES `mydb`.`Sensor` (`Location_Symbol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
