-- MySQL Script generated by MySQL Workbench
-- Thu Feb 18 12:21:44 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Temperature
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Temperature
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Temperature` DEFAULT CHARACTER SET utf8 ;
USE `Temperature` ;

-- -----------------------------------------------------
-- Table `Temperature`.`Time`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Temperature`.`Time` ;

CREATE TABLE IF NOT EXISTS `Temperature`.`Time` (
  `Time_ID` INT NOT NULL AUTO_INCREMENT,
  `Year` INT NOT NULL,
  `Month` INT NOT NULL,
  `Date` INT NOT NULL,
  `Clock_Time` DATETIME NOT NULL,
  PRIMARY KEY (`Time_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Temperature`.`Location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Temperature`.`Location` ;

CREATE TABLE IF NOT EXISTS `Temperature`.`Location` (
  `Symbol` VARCHAR(45) NOT NULL,
  `Location` VARCHAR(45) NOT NULL,
  `GPS.Coordinates` VARCHAR(45) NOT NULL,
  `Elevation` DECIMAL(5) NOT NULL,
  `Aspect` VARCHAR(45) NOT NULL,
  `Topographical_Description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Symbol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Temperature`.`Sensor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Temperature`.`Sensor` ;

CREATE TABLE IF NOT EXISTS `Temperature`.`Sensor` (
  `Serial_Number` INT NOT NULL,
  `Location_Symbol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Serial_Number`),
  INDEX `Location_Symbol_idx` (`Location_Symbol` ASC),
  CONSTRAINT `Location_Symbol`
    FOREIGN KEY (`Location_Symbol`)
    REFERENCES `Temperature`.`Location` (`Symbol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Temperature`.`Measurement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Temperature`.`Measurement` ;

CREATE TABLE IF NOT EXISTS `Temperature`.`Measurement` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Temperature` FLOAT,
  `Time_ID` INT NOT NULL,
  `Sensor_Symbol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Time_ID_idx` (`Time_ID` ASC),
  INDEX `Sensor_Symbol_idx` (`Sensor_Symbol` ASC),
  CONSTRAINT `Time_ID`
    FOREIGN KEY (`Time_ID`)
    REFERENCES `Temperature`.`Time` (`Time_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Sensor_Symbol`
    FOREIGN KEY (`Sensor_Symbol`)
    REFERENCES `Temperature`.`Sensor` (`Location_Symbol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
