INSERT INTO APP.LOCATION VALUES
('BMS', 'Bald Mesa'),
('BBR', 'Beaver Ba Rd Camp'),
('BOR', 'Boren Mesa'),
('BRR', 'Brumley Ridge'),
('BPA', 'Burro Pass'),
('BPT', 'Burro Pass Trail'),
('CCR', 'Chicken Creek'),
('CKL', 'Clark Lake'),
('DIN', 'Dinosaur Tracks'),
('DFM', 'Dry Fork Mill Cr'),
('EDC', 'E. Dark Canyon'),
('EMP', 'E. Mt. Peale'),
('GEP', 'Geyser Pass'),
('GOB', 'Gold Basin'),
('GBR', 'Gold Basin Road'),
('GRV', 'Grandview'),
('HRC', 'Horse Creek'),
('HWY', 'Hwy 46 La Sal'),
('LSP', 'La Sal Pass'),
('LPJ', 'L SAl Pass Jct'),
('LSS', 'La Sal SNOTEL site'),
('LBB', 'Lower Beaver Basin'),
('LGP', 'Lower Geyser Pa Rd'),
('MER', 'Mellenthin E Ridge'),
('MEM', 'Mellenthin Meadows'),
('MOM', 'Moonlight Meadows'),
('MEL', 'Mt. Mellenthin'),
('NPE', 'N. Peale RG'),
('SBM', 'South Beaver Mesa'),
('UBB', 'Upper Beaver Basin'),
('UD1', 'Upper Dark Canyon'),
('UDC', 'Upper Dark Canyon 2'),
('WME', 'Warner Meadows'),
('WFM', 'Wet Fork Mill Cr'),
('OFF', 'Office');
